#server
server:
  port: 8055
#application detail
  spring:
    application:
      name: my-bick-project


#myBatis database pool
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    min-evictable-idle-time-millis: 300000
    validationQuery: select 'x'
    test-while-idle: true
    test-on-borrow: false
    testOnReturn: false
    pool-prepared-statements: true
    max-open-prepared-statements: 20
    url: jdbc:mysql://localhost:3306/db_bick
    username: root
    password: 123456

#mybatis scan xml
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: classpath:com.it.**.entity


  #logback
  logging:
    config: classpath:logback.xml