#server
server:
  port: 8055
#application detail
  spring:
    application:
      name: my-bick-project


#myBatis database pool
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    min-evictable-idle-time-millis: 300000
    validationQuery: select 'x'
    test-while-idle: true
    test-on-borrow: false
    testOnReturn: false
    pool-prepared-statements: true
    max-open-prepared-statements: 20
    url: jdbc:mysql://localhost:3306/db_bick
    username: root
    password: 123456




#mybatis scan xml
mybatis:
  mapper-locations: classpath:com.it.project.**/*.xml
  type-aliases-package: classpath:com.it.project.**.entity


  #logback
  logging:
    config: classpath:logback.xml
#redis
redis:
  host: 127.0.0.1
  port: 6379
  max-idle: 5
  max-total: 10
  max-wait-mills: 3000

#activemq
activemq:
  broker-url: tcp://localhost:61616
  pool:
    enabled: false
#spring-data  mongodb
  data:
    mongodb:
      uri: mongodb://127.0.0.1/bick
